name: Survey Marketplace Install, Test and Build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master


jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.17.0]

    steps:
      - name: Checkout Use Node.js ${{ matrix.node-version}}
        uses: actions/checkout@v2

      - name: Install
        run: |
          yarn
      - name: Test
        run: |
          yarn test 

  deploy:
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
          node-version: [10.17.0]
    
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout use Node.js ${{ matrix.node-version}}
        uses: actions/checkout@v2
        with:
          persist-credential: false
      
      - name: Predeploy
        run: |
          yarn
          yarn predeploy
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3-test
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: master
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
      
      - name: Rename build directory
        run:  |
          mv ./dist ./build

      - name: Deploy to docker
        uses: mr-smithers-excellent/docker-build-push@v2
        with:
          image:  dhruvingbc/survey-marketplace-dapp
          tag: 0.0.${GITHUB_RUN_NUMBER}
          register: docker.io
          dockerfile: "./Dockerfile"
          username: "dhruvingbc"
          password: ${{ secrets.DOCKER_PASSWORD }}

