name: Survey Marketplace Install, Test and Build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master


jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.17.0]

    steps:
      - name: Checkout Use Node.js ${{ matrix.node-version}}
        uses: actions/checkout@v2

      - name: Install
        run: |
          yarn
      - name: Test
        run: |
          yarn test 

  deploy:
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
          node-version: [10.17.0]
    
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout use Node.js ${{ matrix.node-version}}
        uses: actions/checkout@v2
        with:
          persist-credential: false
      
      - name: Predeploy
        run: |
          yarn
          yarn predeploy
      
      - name: Install SSH Client
        uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3-test
        with:
          BASE_BRANCH: master
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
          SSH: true #SSH must be set to true so the deploy action knows which protocol to deploy with

